### PR TITLE
Pop-Up Visual Enhancements

### PR DESCRIPTION
**Pull request by rjaltman**
Contains visual changes to the Pop-ups in Blocked, Not Blocked, and Not Set Up states. Testing was done manually, and position / alignment testing was ignored due to this being a Chrome extension and having fixed window attributes. 

Note that this PR will grow with the changes - it was created when "No Sites Added" was completed as one of the three buttons completed. Also, the buttons do not do anything in this PR, but that may change on request instead of throwing that into another PR.

### CODE REVIEW

**Comment by AcademyInPeril** [comment]
Updated copy and the version number. Functionality will be definitely need to be built out behind the new buttons before this is merged.

**Comment by rjaltman** [comment]
@AcademyInPeril, that functionality should hopefully be ready now. The default behavior is the one we specify on our Options page, which is stop scrolling after 500 pixels. The only thing that does not happen as of yet is that the dialog text does not change, but that should be coming very soon.

**Comment by AcademyInPeril** [comment]
Two bugs with the current setup:

- The changes don't seem to propagate immediately. You seem to have to reload the page for changes to take effect. This also means that a page that has been blanked due to a limit does not unblank once the unlimit button is pressed on the dropdown. Does that seem like something that's fixable without major rewriting of other functionality?

- Once you've used the dropdown button to change a page's behavior, you cannot change that behavior back without closing and re-opening the dropdown first. This is a separate bug than the first one in user flow, but might be tied to the same logic. If you choose to change a site's limit status from the dropdown dialog, you can't change it back while the dropdown is still open.

**Comment by AcademyInPeril** [comment]
Tested and working. This seems to be a perfectly acceptable workaround for the moment.

**Pull request merged**
